# -*- coding: utf-8 -*-
"""Matplotlib_Nb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-Z_UW27rzqpdyckwlhAWQCzUheWCDNA

#Matplotlib
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""#Plotting Line Graphs"""

x = [1,2,3,4]
y = [1,4,9,16]
plt.plot(x, y, color='blue', linewidth=2, linestyle='-', marker='o', label='first line')
plt.title('Line Plot', fontsize=16)
plt.grid(color='green')
plt.xlabel('Numerals')
plt.ylabel('Squares')
plt.legend(loc='lower right')
plt.xticks([1,2,3,4], ['one', 'two', 'three', 'four'])
plt.yticks([1,4,9,16], ['one', 'four', 'nine', 'sixteen'])
plt.show()

"""#Plotting Bar Graphs"""

x = ['A', 'B', 'C', 'D']
y = [800, 1200, 400, 1500]
plt.barh(x, y, color = 'purple', label = 'Sales')
plt.title('Bar Chart', fontsize=16)
plt.xlabel('Categories')
plt.ylabel('Values')
plt.legend(loc='upper left')
plt.show()

"""#Pie Chart"""

regions = ['North', 'East', 'West', 'South']
revenue = [2000, 1000, 3000, 1500]
plt.pie(revenue, labels=regions, autopct='%1.1f%%', colors=['lightgreen', 'gold', 'coral', 'skyblue'])
plt.title('Pie Chart', fontsize=16)
plt.show()

"""#Histograms"""

#plt.hist(data, bins=number_of_bins, color=color, edgecolor=edgecolor, label=label)
scores = [45, 67, 76, 87, 23, 30, 55, 67, 89, 34, 12, 37, 58, 84, 43, 22, 10, 91]
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

plt.hist(scores, bins, color='lightblue', edgecolor='black')
plt.title('Histogram', fontsize=16)
plt.xlabel('Scores')
plt.ylabel('Students')
plt.yticks(np.arange(0,4,1)) #To remove the floating point numbers.
plt.show()

"""#Scattered Graph"""

x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

plt.scatter(x, y, color = 'Orange', label = 'Scatter Graph')
plt.grid(True)
plt.title('Scatter Graph', fontsize=16)
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.legend(loc='upper left')
plt.show()

plt.scatter([1,2,3], [45, 60, 80], color = 'skyblue', label = 'Class A')
plt.scatter([1,2,3], [40, 50, 60], color = 'lightgreen', label = 'Class B')
plt.grid(True)
plt.title('Comparison b/w two', fontsize=16)
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.legend(loc='upper left')
plt.show()

"""#Sub-Plots"""

x = [1,2,3,4]
y = [2,4,6,8]

plt.subplot(1,2,1)
plt.plot(x,y)
plt.title("Line Graph")

plt.subplot(1,2,2)
plt.bar(x,y)
plt.title("Bar Graph")

plt.tight_layout()
plt.show()

fig, ax = plt.subplots(1,2, figsize=(10,5))

ax[0].plot(x,y)
ax[0].set_title("Line Graph")

ax[1].bar(x,y)
ax[1].set_title("Bar Graph")

fig.suptitle('Comparison b/w line and bar graphs')
plt.tight_layout()
plt.show()

"""#Saving a Plotted Graph"""

x = [1,2,3,4]
y = [10,20,30,40]

plt.plot(x,y, color='lightblue', linestyle='-', marker='o')
plt.title('Line Plot', fontsize=16)
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.grid(True)
plt.savefig('line_plot.png', dpi=300, bbox_inches='tight')
plt.show()