# -*- coding: utf-8 -*-
"""Pandas_Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERVD5PTGqg5uVIfGGrL9majwK6qCI8dA
"""

print("Introduction to Pandas")

import numpy as np
import pandas as pd

# Create a sample NumPy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Convert the NumPy array to a DataFrame
df_from_array = pd.DataFrame(numpy_array, columns=['col1', 'col2', 'col3'])

# Display the resulting DataFrame
display(df_from_array)

"""#Pandas has two Data Structures namely:-
1) **Series** (For 1D)\
2) **Data Frames** (For 2D or more)
"""

import pandas as pd
s = pd.Series([23, 12, 34, 54, 56], index = ['a', 'b', 'c', 'd', 'e'])
s

df = pd.DataFrame({'Name': ['Harry', 'Rohan', 'Shubham'], "marks": [84, 45, 67], "GPA": [8.5, 4.5, 7.0]})
df

import numpy as np

# Generate sample data
data = {
    'ID': range(1, 101),
    'Value1': np.random.rand(100) * 100,
    'Value2': np.random.randint(0, 1000, 100)
}

df_sample = pd.DataFrame(data)

# Save to CSV
df_sample.to_csv('sample_data.csv', index=False)

print("sample_data.csv created successfully!")

"""#Reading a CSV file using Pandas"""

df_sample = pd.read_csv('sample_data.csv')
df_sample

"""#Various operations/methods on DataFrames"""

df_sample.head()

df_sample.tail()

df_sample.describe()

df_sample.info()

"""#Data Selection"""

df_sample["ID"]

df_sample[["ID", "Value1"]]

df_sample.iloc[0]

df

def fn(i):
  if i >= 9.0:
    return 'A'
  elif i >= 8.0:
    return 'B'
  elif i >= 6.0:
    return 'C'
  else:
    return 'F'
df['Grade'] = df['GPA'].apply(fn)
df

df.to_csv('grades.csv', index=False)

df1 = pd.DataFrame({'Roll_No': [101, 102, 103]})
df1

pd.merge(df, df1, on="Name")

pd.concat([df, df1], axis=1)

